### PR TITLE
Support regular RN color value, no more crashing after first callback is consumed.

### PR DESCRIPTION
**Pull request by Noitidart**
Please don't merge. I am writing a new API for proposal. I know you might not accept it, but I just wanted to propose it (at least Im using). This will be v2.0 because of so many differences. However it makes it easy for people to use.

### CODE REVIEW

**Comment by aakashns** [comment]
Thanks for taking this up! I was new to React Native when I created this library, so didn't take care to create an idiomatic API. I've wanted to redo the API for a long time, but never got around to doing it. Please also take inputs from @vonovak

**Comment by Noitidart** [comment]
Thank you very much @aakashns for your amazing work! And much thanks for your motivation here! I will definitely chat with vonovak on it, and I hope to merge in the other PRs like #55.

**Comment by vonovak** [comment]
@Noitidart what is the new API proposal I was also thinking the api surface could be nicer, but it ended up not being a priority for me.

I'll just share what I have in mind: instead of 

```js
const dialog = new DialogAndroid();
dialog.set({
  "data": {
    "items": [
      "Twitter",
      "Google+",
      "Instagram",
      "Facebook"
    ],
    "title": "Social Networks",
    itemsCallbackSingleChoice: (id, text) => ToastAndroid.show(id + ": " + text, ToastAndroid.SHORT);
  }
})
```

the more react-way would be 

```js
<Dialog title = "Social Networks" itemsCallbackSingleChoice = {(label, value) => ToastAndroid.show(label + ": " + value, ToastAndroid.SHORT)}>
    <Item label={i18n("dog")} value="dog" />
    <Item label={i18n("cat")} value="cat" />
</Dialog >
```

perhaps both ways could be supported, with the second one just converting the react components into the first one.

**Comment by Noitidart** [comment]
Thanks @vonovak -  I was actually thinking `DialogAndroid` is most similar to RN's [`DatePickerAndroid`](https://facebook.github.io/react-native/docs/datepickerandroid.html).

They treat dialog's as an "API" rather than a "Component". DatePickerAndroid returns a promise so it is used like this:

    const {action, year, month, day} = await DatePickerAndroid.open({ date:new Date(2020, 4, 25) });
    if (action !== DatePickerAndroid.dismissedAction) {
          //
    }

So I have done the same.


Other RN api's it is similar to is very similar to javascripts 'alert', RN's [`Alert`](https://facebook.github.io/react-native/docs/alert.html), [`AlertIOS.alert`](https://facebook.github.io/react-native/docs/alertios.html#alert) and [`AlertIOS.prompt`](https://facebook.github.io/react-native/docs/alertios.html#prompt). These are older APIs so they do not use the Promise model. The Promise model is newer, for use with `async/await`. But following `AlertIOS`, we can have convenience functions like:

* `DialogAndroid.showProgress('message here');`
* `await DialogAndroid.prompt('title', 'message', options)`;

**Comment by vonovak** [comment]
I agree the promise-based interface is an improvement over using callbacks. However, I'm worried that this lib has wider feature set compared to DatePickerAndroid, and treating it in such way is an oversimplification. Plus, the react-like interface has some nice benefits. Let me share some thoughts on what is currently hard, as well as what could be improved with the react-like interface.

* `itemsCallback*Choice`:
consider

```js
  "data": {
    "items": [
      "Cat",
      "Dog",
    ],
    "title": "Animals",
    itemsCallbackSingleChoice: (index, text) => ToastAndroid.show(id + ": " + text, ToastAndroid.SHORT);
  }
```
`itemsCallbackSingleChoice` has the signature of `(index, text) =>void`
where neither index nor text is the stuff you really care about. You do not care about the index because it tells you nothing and you do not care about the text because if you use i18n then the text is different in every language. You care about the underlying "value" which may be some unique identifier for each item. That is why `<Item label={i18n("dog")} value="id-of-dog" />` is a good approach.

An alternative would be 
```js
"items": [
      {label: i18n("cat), value: "cat"},
      {label: i18n("dog), value: "dog"},
    ],
```

* declaratively expressing what is going to be displayed in (for example) present list of values.
Say that you have two user roles: normal user and vip user. You want them to see these options:

normal user: `["margarita", "salami", "hawaii"]`
vip user       : `["margarita", "quattro formaggi", "salami", "hawaii", "pizza burger"]`


with the current api: the `items` array will have to be filled before passed to the `Dialog` module. Let's say that the `pizzas` are passed in as some parameter to `showPizzasDialog` function.

```js
function showPizzasDialog(pizzas) {
  lat pizzasCopy = pizzas.slice() // we will be adding things to the array and do not want to modify the one we got!!
  if (isVipUser) {
    pizzasCopy.splice(2, 0, "quattro formaggi");
    pizzasCopy.splice(4, 0, "pizza burger);
  }

  //show dialog and pass pizzasCopy
}
```
^ you see that ugly imperative code? And god knows what happens if I forget to slice the array. Compare that with:

```js
<Dialog title={i18n("pizzas")} >
  <Item label={i18n("margarita")} value="1" />
  {isVipUser && <Item label={i18n("quattro formaggi")} value="2" />}
  <Item label={i18n("salami")} value="3" />
  <Item label={i18n("hawaii")} value="4" />
  {isVipUser && <Item label={i18n("pizza burger")} value="5" />}
</Dialog >
```

* textinputs that provide `onChangeText` function. The module, theoretically, supports textinputs. Some people are not only interested in the final value that user submits, but also in the intermediate ones eg: https://github.com/aakashns/react-native-dialogs/issues/57. This use case an be beautifully expressed with react components:

```js
<Dialog title={i18n("enter something")} >
  <TextInput placeholder={i18n("enter pizza name")} value="*managed by native dialog / being settable from js (likely not easy)?*" onChangeText=(text=>doSomethingWithText) />
</Dialog >
```

My personal favourite would be having the sort of api we have currently, and also having this react-like api. The react-like api would traverse the react tree of the dialog and extract all the options from it. Then it'd create a simple options object like the one we currently use and pass that over to native.

It's just ideas though, and any improvement is a step forward, so please do what you think is best, I just wanted to share some thoughts.

**Comment by Noitidart** [comment]
I just went through all my instnces of using dialog. I personally cannot find any instance where I work with the "string" value returned. I used the id to find the element in a list of items.

So maybe we should actually deprecate supporting strings as items and enforce items to be array of `{ [idKey]:any, [labelKey]:string }`, where `idKey` and `labelKey` default to "id" and "label" respectively.

**Comment by Noitidart** [comment]
Here is the proposal in a README format, with types:

https://github.com/Noitidart/react-native-dialogs/blob/c8ae05e0984ef39688e3892cc73cbf47e8a94964/README.md

**Comment by Noitidart** [comment]
@vonovak what do you think about that mention of mine? My mention of "component based isn't something even the RN official team does for dialogs. They only did Picker when mode=dropdown as component based because this is actually a physically renedered component in the view hierarchy". So would you be ok with promised based api as we see for RN official dialog apis?

**Comment by vonovak** [comment]
> I like the <Dialog> component idea, however it will require working with state of component.

This would likely not use state, since all of the state would be managed on native side and JS may be informed by events from the native side. Managing state in JS would be possible but quite complicated (synchronizing value of a textinput for example).

> I have not seen any Dialog API that has a component approach

Which does not mean the using the component approach is a bad thing. The component approach does have its advantages, as I have clearly outlined in the previous comment. Take a look at [this module](https://github.com/prscX/react-native-bottom-action-sheet) which offers doing things both ways.

> enforce items to be array of { [idKey]:any, [labelKey]:string }

that sounds reasonable.


> component based isn't something even the RN official team does for dialogs

yes, they do not do that because it would be an overkill: the [RN alert](https://facebook.github.io/react-native/docs/alert.html) has only a title, body and maximum of three buttons. There is no reason to make a component for this, if all you need is a function call with a maximum of 4 parameters. 

Compare the RN alert functionality:

exampleios

with what this module is capable of (the screen on the right is already a complicated UI, placed in a dialog. You'd normally use components to create such kind of thing.):

exampleDialogs

> They only did Picker when mode=dropdown as component based because this is actually a physically renedered component in the view hierarchy.

I think this is misleading; they did not do it the component-way because it is "physically rendered" (see the render method [here](https://github.com/facebook/react-native/blob/70a3ececc368a8d0fe4b57b13ac956ad99a637c7/Libraries/Components/Picker/Picker.js#L66)), they did it because the component-way offers a very nice interface for a programmer to work with. It avoids the stuff I have outlined in my [comment](https://github.com/aakashns/react-native-dialogs/pull/82#issuecomment-377545942) - namely, it keeps you from writing imperative code.

I'll re-state my opinion: My personal favourite would be having the sort of api we have currently, and also having this react-like api. The react-like api would traverse the react tree of the Dialog and extract all the options from it. Then it'd create a options object like the one we currently use and pass that over to native.

However, I do not have time to dedicate to create such API so I believe the changes you're working on will bring an improvement.

**Comment by Noitidart** [comment]
I got you. I'll give a component api a shot. I agree with your point that using components to build this image below is normal:

image

May you please share we currently accomplish this above? I can't figure it out. I'll then work on a component version.

**Comment by Noitidart** [comment]
Hi there @vonovak I didn't make progress on a component based version. How about we accept this PR as a API revisit version, and maybe someone else can come along and add a component based version? I was motivated for the API rewrite, maybe someone else will come along for the component based version?

**Comment by vonovak** [comment]
Yeah, sure!

**Comment by Noitidart** [comment]
Yay thank you! Is there anything you would like me touchup on this PR? It would have to be a major version update, so semantic version, and `npm update` doesnt surprise people.

**Comment by vonovak** [comment]
@Noitidart the PR was too large to review; so I just merged and let's see how it works. Perhaps we should ask @aakashns to add you to the collaborators here. Thanks for the work! Should we do a major release now?

**Comment by aakashns** [comment]
@Noitidart This is looking good! Looking forward to some code examples. Let me know your username on NPM, and I'll add you as a collaborator there.

@vonovak Sure, we can do a major release (1.0). Maybe we can start with a release candidate 1.0.0-rc1, so that developers can try it out and help us identify and fix bugs. I'm looking forward to using this too.

**Comment by Noitidart** [comment]
Thank you @aakashns very very much!!

Another user actualy submitted an awesome PR to added support for "checkbox" in dialogs! Im going to work with him to get it into the js api and with docs - https://github.com/Noitidart/react-native-dialogs/pull/1

**Comment by Noitidart** [comment]
Oops forgot to reply to your other stuff @aakashns 

* My npm username is noitidart - https://www.npmjs.com/~noitidart - thank you very much for considering to add me there!
* Re the code examples, you read my mind! haha I just created a PR with code examples with screenshots - https://github.com/aakashns/react-native-dialogs/pull/83

**Comment by aakashns** [comment]
> My npm username is noitidart - https://www.npmjs.com/~noitidart 
I've added you as a collaborator. Please coordinate with @vonovak before releasing.

Thanks a lot for adding the screenshots & examples!

**Comment by Noitidart** [comment]
Roger that, will for sure work with him.

**Pull request merged**
