### PR TITLE
Added maxNumberOfItems property

### PR DESCRIPTION
**Pull request by eladgel**
I wanted to control the number of items visible on any of the list dialogs
Added the property to the js file, and property handling  in the jave file

### CODE REVIEW

**Comment by Noitidart** [comment]
This is super cool! Thank you for sharing! May you please update the documentation for this.

**Comment by eladgel** [comment]
updated readme @Noitidart

**Comment by Noitidart** [comment]
Thank you very uch @eladgel merging now!

**Comment by Noitidart** [comment]
I'm hoping to fix the install issues for 0.57+ and then roll out 1.0.3 - did you encounter issues when installing into RN >= 0.57?

**Comment by eladgel** [comment]
Im using rn 57.7

**Comment by Noitidart** [comment]
When installing did you have to do any manual modifications after `npm i react-native-dialogs` then `react-native link react-native-dialogs`?

**Pull request merged**
