### PR TITLE
Added screenshots

### PR DESCRIPTION
**Pull request by Noitidart**
This adds screenshots and two small bug fixes.

* screenshots to readme - will not show until merged to master as its using "https://github.com/aakashns/" as image paths
* fixed multi choice, when nothing was selected it was giving [ undefined ]
* no spacing in showProgress when horizontal style

### CODE REVIEW

**Comment by Noitidart** [comment]
Thank you @vonovak !

**Comment by Noitidart** [comment]
Woohoo the images for the code examples are showing! (i guessed on those paths haha) Check it out please @aakashns :)

**Comment by aakashns** [comment]
Looks great! Thanks for the amazing work @Noitidart! 

Please also add a contributors/maintainers sections listing yourself and @vonovak as contributors.

**Comment by Noitidart** [comment]
Thanks @aakashns! :)

**Pull request merged**
