### PR TITLE
implement 'keyboardType' on native side

### PR DESCRIPTION
**Pull request by Phecda**
Hi, I found "keyboardType" really useful but not implemented yet, so I open this PR to share my implementation. This is based on #55 , and I did some changes to match what TextInput behave.

### CODE REVIEW

**Comment by Noitidart** [comment]
This is super cool thank you! Thank you for also updating the documentation. I can't test this right now, but if anyone else can, or if @Phecda you are confident it is thoroughly tested, I am ready to merge.

**Comment by Phecda** [comment]
I find I missed a dependency 😂. Now it works fine on my emulators(API 23 & API 28).

**Comment by Phecda** [comment]
I just test on my phone and it works fine. I think it's ready to be merged. @Noitidart

**Comment by Noitidart** [comment]
Thank you very much @Phecda !! Merging now.

**Pull request merged**
