### PR TITLE
Differentiate OptionsCheckboxList, close #111

### LINKED ISSUE #111: Duplicate type OptionsCheckbox
https://github.com/aakashns/react-native-dialogs/blob/master/DialogAndroid.js#L16 and https://github.com/aakashns/react-native-dialogs/blob/master/DialogAndroid.js#L49 is duplicated.

@aakashns @Noitidart Should they be different?

### PR DESCRIPTION
**Pull request by Noitidart**
Addresses #111 - what do you think @ratson - thanks for the catch.

### CODE REVIEW

**Comment by ratson** [comment]
👍

**Comment by kirillpisarev** [comment]
Should be merged, otherwise it breaks builds on RN 0.59.1

**Comment by Noitidart** [comment]
Roger that thanks folks. Merging now. @kirillpisarev can you test it by installing from master with - 

    npm i github:aakashns/react-native-dialogs#master

**Comment by kirillpisarev** [comment]
With the code from master everything works just fine now, thank you!

> Then I'll do a release. I'm not sure how it's breaking in 0.59.1 though, did they release a flow update, which is identifying this name clash?

Honestly i didn't dive into the problem, but yes, i guess so.

**Comment by Noitidart** [comment]
Thank you! Releasing to npm now.

**Pull request merged**
