### PR TITLE
Add a note how to dismiss dialog without having reference to it

### PR DESCRIPTION
**Pull request by Noitidart**

### CODE REVIEW

**Comment by vonovak** [comment]
I'm just thinking - is this really useful and should it be documented, or is this an implementation detail that people should not rely on? I guess its a useful piece of information, but I'd not want people to rely on this too much...

**Comment by Noitidart** [comment]
Understood. I agree if you want to remove it.

For my case in my form submit handler I show a dialog. And when there is an error, in my `componentDidUpdate()` I don't have reference to the dialog. I had just looked into the native code - https://github.com/aakashns/react-native-dialogs/blob/master/android/src/main/java/com/aakashns/reactnativedialogs/modules/DialogAndroid.java#L345-L352 - so I realized oh my gosh I dont have to hold on to the reference. I had this huge implementation setup where each reference was being held, it was nasty lol.

**Comment by Noitidart** [comment]
Maybe rather then document this. We should add a property method to `DialogAndroid` called `dismissCurrent`.

So they can just do `DialogAndroid.dismissCurrent()` what do you think?

**Comment by Noitidart** [comment]
Alternative here - https://github.com/aakashns/react-native-dialogs/pull/81

**Pull request closed without merging**
